packages:
  - 'apps/*'
  - 'packages/*'
  - 'e2e'

catalog:
  '@prisma/adapter-pg': 7.4.2
  '@prisma/client': 7.4.2
  '@types/express': 5.0.6
  '@types/express-serve-static-core': '5.1.1'
  '@types/node': '25.5.0'
  '@typescript/native-preview': '7.0.0-dev.20260327.2'
  express: 5.2.1
  express-rate-limit: 8.3.2
  prisma: 7.4.2
  tsx: 4.21.0
  typescript: 5.9.3
