import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { createEnv } from '@t3-oss/env-core';
import { config as dotenvConfig } from 'dotenv';
import { z } from 'zod';

import {
  millisecondSchema,
  stringToNumberSchema,
  transformedBooleanSchema,
} from '@tailtown/shared';

const envDir = path.dirname(fileURLToPath(import.meta.url));
const rootEnvPath = path.resolve(envDir, '../../..', '.env');

dotenvConfig({ path: rootEnvPath });

export const env = createEnv({
  server: {
    NODE_ENV: z.enum(['development', 'production', 'test']),
    ALLOWED_ORIGINS: z
      .string()
      .transform((s) => s.split(','))
      .pipe(z.array(z.string().min(1))),
    RATE_LIMIT_WINDOW_MS: stringToNumberSchema,
    RATE_LIMIT_MAX_REQUESTS: stringToNumberSchema,
    DATABASE_SSL_ENABLED: transformedBooleanSchema,
    DATABASE_MAX_CONNECTIONS: stringToNumberSchema,
    DATABASE_IDLE_TIMEOUT: stringToNumberSchema,
    REDIS_URL: z.url(),
    PASSWORD_SALT_ROUNDS: stringToNumberSchema,
    LOG_LEVEL: z.enum(['debug', 'info', 'warn', 'error']),

    CUSTOMER_SERVICE_PORT: stringToNumberSchema,
    CUSTOMER_SERVICE_HOST: z.string().min(1),
    CUSTOMER_SERVICE_TRUST_PROXY: transformedBooleanSchema,
    CUSTOMER_SERVICE_DISABLE_HTTPS_REDIRECT: transformedBooleanSchema,
    CUSTOMER_SERVICE_DATA_DIR: z.string().min(1),
    CUSTOMER_DATABASE_URL: z.url(),
    CUSTOMER_JWT_SECRET: z.string().min(1),
    CUSTOMER_JWT_EXPIRES_IN: millisecondSchema,
    CUSTOMER_JWT_REFRESH_SECRET: z.string().min(1),
    CUSTOMER_JWT_REFRESH_EXPIRES_IN: millisecondSchema,
    CUSTOMER_JWT_REFRESH_TOKEN_EXPIRES_IN: millisecondSchema,
    CUSTOMER_SUPER_ADMIN_JWT_SECRET: z.string().min(1),
    CUSTOMER_SUPER_ADMIN_JWT_EXPIRES_IN: millisecondSchema,
    CUSTOMER_SUPER_ADMIN_REFRESH_EXPIRES_IN: millisecondSchema,
    CUSTOMER_BCRYPT_ROUNDS: stringToNumberSchema,
    CUSTOMER_SESSION_SECRET: z.string().min(1),
    CUSTOMER_ENABLE_2FA: transformedBooleanSchema,
    CUSTOMER_SUPER_ADMIN_API_KEY: z.string().min(1),
    CUSTOMER_SERVICE_API_KEY: z.string().min(1),
    CUSTOMER_ALLOWED_METHODS: z.string().min(1),
    CUSTOMER_ALLOWED_HEADERS: z.string().min(1),
    CUSTOMER_ALLOW_CREDENTIALS: transformedBooleanSchema,
    CUSTOMER_API_PREFIX: z.string().min(1),
    CUSTOMER_API_VERSION: z.string().min(1),
    CUSTOMER_ENABLE_API_DOCS: transformedBooleanSchema,
    CUSTOMER_RATE_LIMIT_WINDOW: stringToNumberSchema,
    CUSTOMER_RATE_LIMIT_SKIP_TRUSTED: transformedBooleanSchema,
    CUSTOMER_UPLOAD_PATH: z.string().min(1),
    CUSTOMER_UPLOAD_DIR: z.string().min(1),
    CUSTOMER_MAX_FILE_SIZE: stringToNumberSchema,
    CUSTOMER_ALLOWED_FILE_TYPES: z.string().min(1),
    CUSTOMER_SCAN_UPLOADS_FOR_MALWARE: transformedBooleanSchema,
    CUSTOMER_LOG_FORMAT: z.string().min(1),
    CUSTOMER_LOG_TO_FILE: transformedBooleanSchema,
    CUSTOMER_LOG_FILE: z.string().min(1),
    CUSTOMER_LOG_FILE_PATH: z.string().min(1),
    CUSTOMER_REDIS_PASSWORD: z.string().optional(),
    CUSTOMER_CACHE_TTL: stringToNumberSchema,
    CUSTOMER_SMTP_HOST: z.string().min(1),
    CUSTOMER_SMTP_PORT: stringToNumberSchema,
    CUSTOMER_SMTP_USER: z.string().min(1),
    CUSTOMER_SMTP_PASSWORD: z.string().min(1),
    CUSTOMER_FROM_EMAIL: z.string().min(1),
    CUSTOMER_SENDGRID_API_KEY: z.string().optional(),
    CUSTOMER_SENDGRID_FROM_EMAIL: z.string().min(1),
    CUSTOMER_SENDGRID_FROM_NAME: z.string().min(1),
    CUSTOMER_ENABLE_METRICS: transformedBooleanSchema,
    CUSTOMER_METRICS_PORT: stringToNumberSchema,
    CUSTOMER_SENTRY_DSN: z.string().optional(),

    CUSTOMER_TEST_DATABASE_URL: z.url().optional(),

    RESERVATION_SERVICE_URL: z.url().default('http://localhost:4003'),
    PAYMENT_SERVICE_URL: z.url().default('http://localhost:4005'),
    FRONTEND_URL: z.url().default('https://tailtown.canicloud.com'),
    BUSINESS_NAME: z.string().default('Tailtown Pet Resort'),
    BUSINESS_PHONE: z.string().optional(),
    GINGR_SUBDOMAIN: z.string().default('tailtownpetresort'),
    GINGR_API_KEY: z.string().optional(),
    TWILIO_ACCOUNT_SID: z.string().optional(),
    TWILIO_AUTH_TOKEN: z.string().optional(),
    TWILIO_API_KEY_SID: z.string().optional(),
    TWILIO_API_KEY_SECRET: z.string().optional(),
    TWILIO_PHONE_NUMBER: z.string().optional(),
    DEBUG_PRISMA: transformedBooleanSchema.default(false),
    TEST_TENANT_ID: z.string().default('dev'),
    TENANT_ID: z.string().default('dev'),
    MAX_CONCURRENT_SESSIONS: stringToNumberSchema.default(10),
    SENTRY_ENABLED: transformedBooleanSchema.default(false),
    SENTRY_RELEASE: z.string().default('customer-service@1.0.0'),
    REDIS_ENABLED: transformedBooleanSchema.default(true),
  },
  runtimeEnvStrict: {
    NODE_ENV: process.env.NODE_ENV,
    ALLOWED_ORIGINS: process.env.ALLOWED_ORIGINS,
    RATE_LIMIT_WINDOW_MS: process.env.RATE_LIMIT_WINDOW_MS,
    RATE_LIMIT_MAX_REQUESTS: process.env.RATE_LIMIT_MAX_REQUESTS,
    DATABASE_SSL_ENABLED: process.env.DATABASE_SSL_ENABLED,
    DATABASE_MAX_CONNECTIONS: process.env.DATABASE_MAX_CONNECTIONS,
    DATABASE_IDLE_TIMEOUT: process.env.DATABASE_IDLE_TIMEOUT,
    REDIS_URL: process.env.REDIS_URL,
    PASSWORD_SALT_ROUNDS: process.env.PASSWORD_SALT_ROUNDS,
    LOG_LEVEL: process.env.LOG_LEVEL,

    CUSTOMER_SERVICE_PORT: process.env.CUSTOMER_SERVICE_PORT,
    CUSTOMER_SERVICE_HOST: process.env.CUSTOMER_SERVICE_HOST,
    CUSTOMER_SERVICE_TRUST_PROXY: process.env.CUSTOMER_SERVICE_TRUST_PROXY,
    CUSTOMER_SERVICE_DISABLE_HTTPS_REDIRECT:
      process.env.CUSTOMER_SERVICE_DISABLE_HTTPS_REDIRECT,
    CUSTOMER_SERVICE_DATA_DIR: process.env.CUSTOMER_SERVICE_DATA_DIR,
    CUSTOMER_DATABASE_URL: process.env.CUSTOMER_DATABASE_URL,
    CUSTOMER_JWT_SECRET: process.env.CUSTOMER_JWT_SECRET,
    CUSTOMER_JWT_EXPIRES_IN: process.env.CUSTOMER_JWT_EXPIRES_IN,
    CUSTOMER_JWT_REFRESH_SECRET: process.env.CUSTOMER_JWT_REFRESH_SECRET,
    CUSTOMER_JWT_REFRESH_EXPIRES_IN:
      process.env.CUSTOMER_JWT_REFRESH_EXPIRES_IN,
    CUSTOMER_JWT_REFRESH_TOKEN_EXPIRES_IN:
      process.env.CUSTOMER_JWT_REFRESH_TOKEN_EXPIRES_IN,
    CUSTOMER_SUPER_ADMIN_JWT_SECRET:
      process.env.CUSTOMER_SUPER_ADMIN_JWT_SECRET,
    CUSTOMER_SUPER_ADMIN_JWT_EXPIRES_IN:
      process.env.CUSTOMER_SUPER_ADMIN_JWT_EXPIRES_IN,
    CUSTOMER_SUPER_ADMIN_REFRESH_EXPIRES_IN:
      process.env.CUSTOMER_SUPER_ADMIN_REFRESH_EXPIRES_IN,
    CUSTOMER_BCRYPT_ROUNDS: process.env.CUSTOMER_BCRYPT_ROUNDS,
    CUSTOMER_SESSION_SECRET: process.env.CUSTOMER_SESSION_SECRET,
    CUSTOMER_ENABLE_2FA: process.env.CUSTOMER_ENABLE_2FA,
    CUSTOMER_SUPER_ADMIN_API_KEY: process.env.CUSTOMER_SUPER_ADMIN_API_KEY,
    CUSTOMER_SERVICE_API_KEY: process.env.CUSTOMER_SERVICE_API_KEY,
    CUSTOMER_ALLOWED_METHODS: process.env.CUSTOMER_ALLOWED_METHODS,
    CUSTOMER_ALLOWED_HEADERS: process.env.CUSTOMER_ALLOWED_HEADERS,
    CUSTOMER_ALLOW_CREDENTIALS: process.env.CUSTOMER_ALLOW_CREDENTIALS,
    CUSTOMER_API_PREFIX: process.env.CUSTOMER_API_PREFIX,
    CUSTOMER_API_VERSION: process.env.CUSTOMER_API_VERSION,
    CUSTOMER_ENABLE_API_DOCS: process.env.CUSTOMER_ENABLE_API_DOCS,
    CUSTOMER_RATE_LIMIT_WINDOW: process.env.CUSTOMER_RATE_LIMIT_WINDOW,
    CUSTOMER_RATE_LIMIT_SKIP_TRUSTED:
      process.env.CUSTOMER_RATE_LIMIT_SKIP_TRUSTED,
    CUSTOMER_UPLOAD_PATH: process.env.CUSTOMER_UPLOAD_PATH,
    CUSTOMER_UPLOAD_DIR: process.env.CUSTOMER_UPLOAD_DIR,
    CUSTOMER_MAX_FILE_SIZE: process.env.CUSTOMER_MAX_FILE_SIZE,
    CUSTOMER_ALLOWED_FILE_TYPES: process.env.CUSTOMER_ALLOWED_FILE_TYPES,
    CUSTOMER_SCAN_UPLOADS_FOR_MALWARE:
      process.env.CUSTOMER_SCAN_UPLOADS_FOR_MALWARE,
    CUSTOMER_LOG_FORMAT: process.env.CUSTOMER_LOG_FORMAT,
    CUSTOMER_LOG_TO_FILE: process.env.CUSTOMER_LOG_TO_FILE,
    CUSTOMER_LOG_FILE: process.env.CUSTOMER_LOG_FILE,
    CUSTOMER_LOG_FILE_PATH: process.env.CUSTOMER_LOG_FILE_PATH,
    CUSTOMER_REDIS_PASSWORD: process.env.CUSTOMER_REDIS_PASSWORD,
    CUSTOMER_CACHE_TTL: process.env.CUSTOMER_CACHE_TTL,
    CUSTOMER_SMTP_HOST: process.env.CUSTOMER_SMTP_HOST,
    CUSTOMER_SMTP_PORT: process.env.CUSTOMER_SMTP_PORT,
    CUSTOMER_SMTP_USER: process.env.CUSTOMER_SMTP_USER,
    CUSTOMER_SMTP_PASSWORD: process.env.CUSTOMER_SMTP_PASSWORD,
    CUSTOMER_FROM_EMAIL: process.env.CUSTOMER_FROM_EMAIL,
    CUSTOMER_SENDGRID_API_KEY: process.env.CUSTOMER_SENDGRID_API_KEY,
    CUSTOMER_SENDGRID_FROM_EMAIL: process.env.CUSTOMER_SENDGRID_FROM_EMAIL,
    CUSTOMER_SENDGRID_FROM_NAME: process.env.CUSTOMER_SENDGRID_FROM_NAME,
    CUSTOMER_ENABLE_METRICS: process.env.CUSTOMER_ENABLE_METRICS,
    CUSTOMER_METRICS_PORT: process.env.CUSTOMER_METRICS_PORT,
    CUSTOMER_SENTRY_DSN: process.env.CUSTOMER_SENTRY_DSN,

    CUSTOMER_TEST_DATABASE_URL: process.env.CUSTOMER_TEST_DATABASE_URL,

    RESERVATION_SERVICE_URL: process.env.RESERVATION_SERVICE_URL,
    PAYMENT_SERVICE_URL: process.env.PAYMENT_SERVICE_URL,
    FRONTEND_URL: process.env.FRONTEND_URL,
    BUSINESS_NAME: process.env.BUSINESS_NAME,
    BUSINESS_PHONE: process.env.BUSINESS_PHONE,
    GINGR_SUBDOMAIN: process.env.GINGR_SUBDOMAIN,
    GINGR_API_KEY: process.env.GINGR_API_KEY,
    TWILIO_ACCOUNT_SID: process.env.TWILIO_ACCOUNT_SID,
    TWILIO_AUTH_TOKEN: process.env.TWILIO_AUTH_TOKEN,
    TWILIO_API_KEY_SID: process.env.TWILIO_API_KEY_SID,
    TWILIO_API_KEY_SECRET: process.env.TWILIO_API_KEY_SECRET,
    TWILIO_PHONE_NUMBER: process.env.TWILIO_PHONE_NUMBER,
    DEBUG_PRISMA: process.env.DEBUG_PRISMA,
    TEST_TENANT_ID: process.env.TEST_TENANT_ID,
    TENANT_ID: process.env.TENANT_ID,
    MAX_CONCURRENT_SESSIONS: process.env.MAX_CONCURRENT_SESSIONS,
    SENTRY_ENABLED: process.env.SENTRY_ENABLED,
    SENTRY_RELEASE: process.env.SENTRY_RELEASE,
    REDIS_ENABLED: process.env.REDIS_ENABLED,
  },
  clientPrefix: 'PUBLIC_',
  client: {},
  emptyStringAsUndefined: true,
  createFinalSchema: (shape) => z.object(shape),
});
